# DAOS client configuration file.
#
# Location of this configuration file is determined by first checking for the
# path specified through the -o option of the daos_agent command line.
# Otherwise, /etc/daos.yml is used.
#
# Section describing the client configuration
#
# Although not supported for now, one might want to connect to multiple
# DAOS installations from the same node in the future.
#
# Specify the associated DAOS systems.
# Name must match name specifed in the daos_server.yml file on the server.
#
# # default: daos
name: daos

#
#  # Path to client certificate and key file.
#  # Discarded if no CA certificate is passed.
#  #
#  # default: ./.daos/daos.{crt,key}
# cert: ./.daos/daos.crt
# key: ./.daos/daos.key

#
## Use the given directory for creating unix domain sockets
#
## DAOS Agent and DAOS Server both use unix domain sockets for communication
## with other system components. This setting is the base location to place
## the sockets in.
#
## default: /var/run/daos_agent
runtime_dir: /var/run/daos_agent

## default: /tmp/daos_agent.log
log_file: /tmp/daos_agent.log
