# DAOS agent configuration file.
#
# Location of this configuration file is determined by first checking for the
# path specified through the -o option of the daos_agent command line.
# Otherwise, /etc/daos.yml is used.
#
# Section describing the client configuration
#
# Although not supported for now, one might want to connect to multiple
# DAOS installations from the same node in the future.
#
# Specify the associated DAOS systems.
# Name must match name specifed in the daos_server.yml file on the server.
#
# # default: daos
name: daos

#
#  TODO: Rework this description
#
#  # Access points
#  # To operate, DAOS will need a quorum of access point nodes to be available.
#  # Hosts can be specified with or without port, default port below.
#  #
#  # default: ??? TBD
#  # access_pts: [hostname1,hostname2,hostname3]
access_points: ['hostname1:10001','hostname2:10001','hostname3:10001']

#
# TODO: Rework this description
#
#  # Force default port number to connect to daos_server, this will also
#  # be used when connecting to access points if no port is specified.
#  #
#  # default: 10000
port: 10000

#
#  # Path to CA certificate
#  # Not required if the DAOS server is configured in an insecured way
#  #
# # default: ./.daos/ca.crt
ca_cert: ./.daos/ca.crt

#
#  # Path to client certificate and key file.
#  # Discarded if no CA certificate is passed.
#  #
#  # default: ./.daos/daos.{crt,key}
cert: ./.daos/daos.crt
key: ./.daos/daos.key

#
## Use specific OFI interface and port
#
## Specify the single fabric interface used by the client to connect with the DAOS server.
# # default: The fabric interface is autodetected.  Specify a value to override.
fabric_iface: qib0
## Specify the fabric interface port to use with the fabric_iface chosen above
fabric_iface_port: 20000

#
## Use specific OFI provider
#
## Specify the provider that matches the DAOS server.
## ofi+psm2 for Omni-Path, ofi+verbs;ofi_rxm for Infiniband/RoCE and finally
## ofi+socket for non-RDMA-capable Ethernet.
#
# # default: ??? TBD
provider: ofi+socket

#
## Use the given directory for creating unix domain sockets
#
## DAOS Agent and DAOS Server both use unix domain sockets for communication
## with other system components. This setting is the base location to place
## the sockets in.
#
# TODO: validate this default value
## default: /var/run/daos_agent
socket_dir: /var/run/daos_agent
